-- 코드를 입력하세요

# 상반기 아이스크림(FIRST_HALF)의 아이스크림의 맛(FLAVOR) 조회
# 상반기 아이스크림(FIRST_HALF)의 총주문량(TOTAL_ORDER) > 3000
# 아이스크림의 성분 정보(ICECREAM_INFO)의 주 성분(INGREDITENT_TYPE)이 과일

SELECT FLAVOR FROM FIRST_HALF WHERE TOTAL_ORDER > 3000 AND 
FLAVOR IN (SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based')
order by TOTAL_ORDER desc;