-- 코드를 입력하세요
SELECT
    ri.REST_ID as REST_ID,
    ri.REST_NAME as REST_NAME,
    ri.FOOD_TYPE as FOOD_TYPE,
    ri.FAVORITES as FAVORITES,
    ri.ADDRESS as ADDRESS,
    ROUND(AVG(rr.REVIEW_SCORE), 2) as SCORE
FROM 
    REST_INFO ri
JOIN 
    REST_REVIEW rr
ON 
    ri.REST_ID = rr.REST_ID
GROUP BY 
    ri.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;