SELECT
    mp.MEMBER_ID, mp.MEMBER_NAME, mp.GENDER, DATE_FORMAT(mp.DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE mp
WHERE 
    MONTH(mp.DATE_OF_BIRTH) = 3 
    and mp.TLNO IS NOT NULL
    and mp.GENDER = 'W'
ORDER BY mp.MEMBER_ID ASC;

