-- 코드를 입력하세요
# 2021년에 출판된 인문 카테고리
# BOOK_ID, PUBLISHED_DATE 출력
# 출판일 기준으로 오름차순

# SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%y-%m-%d") as PUBLISHED_DATE 
# from BOOK 
# where CATEGORY = '인문' and YEAR(PUBLISHED_DATE) = 2021
# order by PUBLISHED_DATE;

SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE)='2021' AND CATEGORY='인문'
ORDER BY PUBLISHED_DATE